# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  daxparser-benchmarks:
    dependencies:
    - base
    - megaparsec
    - daxparser
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: DaxParser.hs
    source-dirs: benchmark
category: Other
description: daxparser is a DAX parser
executables:
  daxparser:
    dependencies:
    - base
    - megaparsec
    - daxparser
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: DaxParser.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tycho01/daxparser
library:
  dependencies:
  - base
  - attoparsec
  source-dirs: library
license: MIT
maintainer: Tycho Grouwstra
name: daxparser
synopsis: a DAX parser
tests:
  daxparser-test-suite:
    dependencies:
    - base
    - daxparser
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: DaxParser.hs
    source-dirs: test-suite
version: '0.0.0'
